# Site settings
title: Graham Parsons
email: graham@grahamrp.com
description: "Data analysis, visualisation and statistics in Higher Education."
baseurl: ""
url: "https://grahamrp.github.io/"

# Includes an icon in the footer for each user name you enter
footer-links:
    github: grahamrp
    twitter: GRPeely

# Build settings
markdown: kramdown
permalink: pretty

